### ISSUE TITLE
Compression Method and Sampling Rate

### ISSUE THREAD

**Issue by sayment** [pradeesi/play_audio_over_phone_line#1]
Hi,

I am not using Usrobotics's USB modem. I did the changes with `minicom`, change the baud rate in the source code according to settings in `minicom` and changed the compression method. 128 did not work for me. I just simply set it to default(129). 
When i run the script, i get two error. One is after `ATZ3` command and second is `Unable reset to factory default`. But it worked anyway. 
When i call the landline number, it's working as expected. But when it answers the call, i heard just noisy sound. I recorded another wav files with `signed 16-bit PCM` encoding and 8KHz sampling rate nothing changed. 

Analog USB modem i am using is: [https://urun.n11.com/adaptor-ve-cevirici/usb-fax-modem-hat-cikisli-56k-v92-v90-P210931619?gclid=Cj0KCQiAhKviBRCNARIsAAGZ7Ce3E29xGvqj5zLjo9IhE0b_uuVjn2mOOYeZSfhEyrAej7THEXBJSlYaAq39EALw_wcB&gclsrc=aw.ds](url)

Manufacturer is shown as Conexant in dmesg. In the description of the product page supported sampling rate and compression methods is: 
`Support 8-bit U-Law/A-Law coding(G.711)and 8/16bit linear coding
Support 8KHz sampling rate`

I am not sure but i think it can be datasheet of the chipset: [https://www.verical.com/datasheet/conexant-systems-modem-module-cx93010-21z-374396.pdf](url)

I tired something according to supported method but it did not work. Could you help me to find right settings? 

Regards,
Samet

**Comment by thegroundhogwhisperer** [comment]
Hello Samet,

The ATZ3 command is a modem reset command specifying a specific factory default profile.  Please see the following list of AT modem commands and take note that a modem can have multiple factory default profiles. (e.g. ATZ1, ATZ2, etc.)  https://support.usr.com/support/3cxm756/3cxm756-ug/atcoms.htm  Simply remove the 3 from the ATZ3 command and use the default ATZ command to reset your modem to its factory defaults.

I often have problems converting/resampling audio files to a format a voice modem will play correctly.  To convert your .wav files try using SoX - Sound eXchange, the Swiss Army knife of audio manipulation.  

SoX is available here:  http://sox.sourceforge.net/ 

Below is an example of using SoX to resample a .wav file at and 8-bit unsigned sample rate. I use this method to resample all audio before I play the audio file using a voice modem:

/usr/bin/sox input.wav, '-r', '8000', '-e', 'unsigned', output.wav

Here is an example in Python using SoX to resample audio files that are played over a phone line using voice modem.

https://github.com/thegroundhogwhisperer/Ay-yahs-Greenhouse/blob/60e9375a1e5f877bd988e8297af005a64cba46d9/Greenhousestatusttsrttysstvpots/greenhousestatusttsrttysstvpots.py#L371

Regards,
The Groundhog Whisperer

**Comment by sayment** [comment]
> Hello Samet,
> 
> The ATZ3 command is a modem reset command specifying a specific factory default profile. Please see the following list of AT modem commands and take note that a modem can have multiple factory default profiles. (e.g. ATZ1, ATZ2, etc.) https://support.usr.com/support/3cxm756/3cxm756-ug/atcoms.htm Simply remove the 3 from the ATZ3 command and use the default ATZ command to reset your modem to its factory defaults.
> 
> I often have problems converting/resampling audio files to a format a voice modem will play correctly. To convert your .wav files try using SoX - Sound eXchange, the Swiss Army knife of audio manipulation.
> 
> SoX is available here: http://sox.sourceforge.net/
> 
> Below is an example of using SoX to resample a .wav file at and 8-bit unsigned sample rate. I use this method to resample all audio before I play the audio file using a voice modem:
> 
> /usr/bin/sox input.wav, '-r', '8000', '-e', 'unsigned', output.wav
> 
> Here is an example in Python using SoX to resample audio files that are played over a phone line using voice modem.
> 
> https://github.com/thegroundhogwhisperer/Ay-yahs-Greenhouse/blob/60e9375a1e5f877bd988e8297af005a64cba46d9/Greenhousestatusttsrttysstvpots/greenhousestatusttsrttysstvpots.py#L371
> 
> Regards,
> The Groundhog Whisperer

@thegroundhogwhisperer thanks for your reply.
I was converting prerecorded audios using Audacity. I'll try SoX. 
Regards.
